services:
  frontend:
    build: ./front-ecommerce/vite-project
    container_name: frontend-container
    ports:
      - "5173:5173"
    volumes:
      - ./front-ecommerce/vite-project:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "1000:1000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    command: npm run dev -- --legacy-watch
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql-data:
